apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: airflow
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: airflow
    version: 0.2.3
    description: DAG-based dependency aware job scheduler
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/eb88ca01-21d6-464f-8fd5-f481b385c166/airflow.png?v=63798438225
    
