apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  description: monitoring gcp setup
  version: 0.1.1
spec:
  dependencies:
  - name: gcp-bootstrap
    repo: bootstrap
    type: terraform
    version: '>= 0.1.1'
  providers:
  - gcp
